# Site settings
title: Fabio Rubinacci CV
email: dev@fabiorubinacci.com
description: >
  I'm Fabio Rubinacci a Web developer. Nice to meet you!
baseurl: "/"
url: "https://fabiorubinacci.com"
github_username:  xochipi

# Collections
collections:
  works:
  educations:

# Build settings
markdown: kramdown
